Repository roundbroker/roundbroker, pull requests merged in 2018-06, with the labels that each got.

#17 A bunch of fixes and improvements
  webapp/migrations/versions/69234aa61a1f_.py
  webapp/turntable/exceptions.py
  webapp/turntable/member_business.py
  webapp/turntable/models.py
  webapp/turntable/pivot/resources.py
  webapp/turntable/visitor_business.py
  webapp/turntable/web/forms.py
  webapp/turntable/web/resources.py
  webapp/turntable/web/static/assets/js/live.js
  webapp/turntable/web/templates/web/consumer_details.html
  webapp/turntable/web/templates/web/new_consumer.html
  webapp/turntable/web/templates/web/new_generic_consumer.html
  webapp/turntable/web/templates/web/pivot_details.html
  webapp/turntable/web/templates/web/producer_details.html
  webapp/turntable/web/templates/web/struct/layout.html
  webapp/turntable/web/templates/web/struct/layout_pivot.html
Labels: enhancement

#20 Webapp: Fix the new `WebCall` mechanism.
  webapp/turntable/models.py
  webapp/turntable/pivot/resources.py
Labels: bug

#18 Enhance SQLAlchemy database model
  webapp/migrations/versions/69234aa61a1f_.py
  webapp/turntable/models.py
Labels: enhancement

#19 Enhance Docker stack: add PostgreSQL, configure reverse proxy for Nchan and add a first client
  README.md
  docker-compose.yaml
  reverse_proxy/nginx/default.conf
  webapp/.dockerignore
  webapp/Dockerfile
  webapp/requirements.txt
Labels: enhancement

#23 Add nchan authentication and dynamic channel ID
  README.md
  docker-compose.yaml
  nchan/nginx/default.conf
  reverse_proxy/nginx/default.conf
  webapp/turntable/__init__.py
  webapp/turntable/exceptions.py
  webapp/turntable/nchancb/__init__.py
  webapp/turntable/nchancb/resources.py
  webapp/turntable/produce/__init__.py
  webapp/turntable/produce/resources.py
  webapp/turntable/produce/verifier.py
  webapp/turntable/visitor_business.py
Labels: enhancement

#25 feat(webapp): a first glimpse on user profil edition
  webapp/turntable/member_business.py
  webapp/turntable/web/forms.py
  webapp/turntable/web/resources.py
  webapp/turntable/web/templates/web/index_member.html
Labels: enhancement

#24 Add/support sse offset
  client/cli/turnt/cmd/collect.go
  client/cli/turnt/cmd/root.go
  client/sse/sse.go
  client/turnt/state.go
  client/turnt/worker.go
Labels: enhancement

#29 feat(publish): requests are transformed into mattermost queries
  webapp/turntable/produce/resources.py
Labels: enhancement

#35 add(client) add insecure tls support for client connection
  client/Dockerfile
  client/README.md
  client/cli/rb/cmd/collect.go
  client/cli/rb/cmd/root.go
  client/rb/worker.go
Labels: bug, enhancement
